[Definitions]

    [Definitions.same_file_definition]
    Request.TextDocument = "src/uses_header.c"
    Request.Position = { Line = 6, Character = 8 }

    Response.TextDocument = "src/uses_header.c"
    Response.Range.Start.Line = 11
    Response.Range.Start.Character = 5
    Response.Range.End.Line = 10
    Response.Range.End.Character = 22
