[Definitions]

    [Definitions.init_var_dict]
    Request.TextDocument = "neovim/src/nvim/eval.c"
    Request.Position = { Line = 327, Character = 8 }

    Response.TextDocument = "neovim/src/nvim/eval.c"
    Response.Range.Start.Line = 8854
    Response.Range.Start.Character = 5
    Response.Range.End.Line = 8854
    Response.Range.End.Character = 18

    [Definitions.find_window_by_handle]
    Request.TextDocument = "neovim/src/nvim/api/window.c"
    Request.Position = { Line = 30, Character = 25 }

    Response.TextDocument = "neovim/src/nvim/api/private/helpers.c"
    Response.Range.Start.Line = 642
    Response.Range.Start.Character = 7
    Response.Range.End.Line = 642
    Response.Range.End.Character = 28
