[Definitions]

    [Definitions.example]
    Request.TextDocument = "src/uses_header.c"
    Request.Position.Line = 6
    Request.Position.Character = 8

    [Definitions.other]
    Request.TextDocument = "src/uses_header.c"
    Request.Position.Line = 6
    Request.Position.Character = 8
